version: '3'

services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/src
    ports:
      - 8002:8000
